# HUK MCP Echo Server Configuration
host:
  name: "chuk-echo-mcp-server"
  log_level: "INFO"

server:
  type: "stdio"  # Options: stdio, websocket

mcp_servers:
  echo_server:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_echo_server.tools"